import assert from 'node:assert/strict';
import { Reactor, REACTOR } from '../js/reactor.js';

const r = new Reactor();
const center = [{ x: 0, z: 0 }];
assert.equal(r.tick(23, 1, center, []), false);
assert.equal(r.charge, 0);
assert.equal(r.tick(24, 3, center, []), false);
assert.equal(r.charge, 3);
r.tick(27, 1, [], []);
assert.equal(r.charge, 2.6);
r.tick(28, 1, center, center);
assert.equal(r.contested, true);
assert.ok(Math.abs(r.charge - 2.9) < 0.001);
assert.equal(r.tick(32, 4.2, center, []), true);
assert.equal(r.captures, 1);
assert.equal(r.buffLeft, REACTOR.buff);
assert.equal(r.tick(33, 1, center, []), false, 'one reward per cycle');
assert.equal(r.captures, 1);
r.tick(62, 1, center, []);
assert.equal(r.phase, 'waiting');
assert.equal(r.buffLeft, 0);
r.tick(109, 2, [...center, ...center, ...center, ...center], []);
assert.equal(r.phase, 'active');
assert.equal(r.charge, 3, 'co-op bonus caps at 50%');
r.reset();
r.tick(61.9, 0.1, [], []);
r.tick(62, 1, center, []);
assert.equal(r.charge, 0, 'expired windows cannot be captured');
r.reset();
assert.equal(r.captures, 0);
assert.equal(r.completedCycle, -1);
assert.deepEqual(new Reactor().snapshot(), r.snapshot());
console.log('✓ Reactor timing, decay, interference, team bonus, reward dedup, expiry, restart');
